//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldingShare
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Symbol { get; set; }
        public long Volume { get; set; }
        public double Price { get; set; }
    
        public virtual User User { get; set; }
    }
}
