//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using LiveCharts.Defaults;
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDaily : OhlcPoint
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public System.DateTime Date { get; set; }
        public string Volume { get; set; }
        public double Vwap { get; set; }
        public double ChangeOverTime { get; set; }
    }
}
