//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedTrading
    {
        public ReservedTrading() { }
        public ReservedTrading(int companyId,int userId, TradeEnum trade, string quantityStr,
              string minPriceStr, string maxPriceStr,
              DateTime pickDate, DateTime pickTime)
        {
            CompanyId = companyId;
            UserId = userId;
            TradeType = trade.ToString();
            SetMinMaxPrice(minPriceStr, maxPriceStr);
            SetDueDateTime(pickDate, pickTime);
            SetValume(quantityStr);
            DateTime = DateTime.Now;
        }
        void SetMinMaxPrice(string minPriceStr, string maxPriceStr)
        {
            double minPrice;
            if (!double.TryParse(minPriceStr, out minPrice))
            {
                throw new ArgumentException("MinPrice is not valid");
            }

            double maxPrice;
            if (maxPriceStr == "") { maxPrice = double.MaxValue; }
            else
            {
                if (!double.TryParse(maxPriceStr, out maxPrice))
                {
                    throw new ArgumentException("MaxPrice is not valid");
                }
                if(minPrice > maxPrice)
                {
                    throw new ArgumentException("MaxPrice must be smaller than MinPrice");
                }
            }

            MinPrice = minPrice;
            MaxPrice = maxPrice;
        }
        void SetDueDateTime(DateTime pickDate, DateTime pickTime)
        {
            const int closingHour = 16;
            if (pickDate == null) { throw new ArgumentException("Choose Date"); }
            if (pickDate.CompareTo(DateTime.Now.Date) < 0) { throw new ArgumentException("Choose Date(today or later)"); }

            if (pickTime == null)
            {
                DueDateTime = pickDate.AddHours(closingHour);
            }
            else
            {
                DueDateTime = pickDate.AddHours(pickTime.Hour).AddMinutes(pickTime.Minute);

            }
        }
        void SetValume(string quantityStr)
        {
            int quantity;
            if(!int.TryParse(quantityStr,out quantity))
            {
                throw new ArgumentException("Quantity is not valid");
            }
            if(quantity <= 0)
            {
                throw new ArgumentException("Quantity is not valid");
            }
            Volume = quantity;
        }

        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public double MinPrice { get; set; }
        public double MaxPrice { get; set; }
        public long Volume { get; set; }
        public string TradeType { get; set; }
        public System.DateTime DueDateTime { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
