//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingRecord
    {
        public TradingRecord() { }
        public TradingRecord(ReservedTrading reservedTrading, double price)
        {
            UserId = reservedTrading.UserId;
            DateTime = DateTime.Now;
            Price = price;
            Volume = reservedTrading.Volume;
            TradeType = reservedTrading.TradeType.ToString();
            CompanyId = reservedTrading.CompanyId;
        }
        public override string ToString()
        {
            return $"{TradeType}  Price: ${Price.ToString("N2")}, Valume: {Volume}";
        }

        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Price { get; set; }
        public long Volume { get; set; }
        public string TradeType { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
