//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMonitor
{
    using LiveCharts.Defaults;
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuoteDaily : OhlcPoint
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
    }
}
